### PR TITLE
Sync AOSPA-L branch with CM

### PR DESCRIPTION
**Pull request by someone755**

### CODE REVIEW

**Comment by SaatvikShukla** [comment]
lollipop-mr1 branch was inline with cm sources.

**Comment by someone755** [comment]
Oh, sorry about that. Had my local stuff set up to the cm-12.1 branch as I didn't even notice we had a PA-standard-named lollipop-mr1.
(Should/could we get somebody to set lollipop-mr1 to be the default?)

**Comment by SaatvikShukla** [comment]
Perhaps, @Ayysir  or @SferaDev could do that.

**Comment by axsddlr** [comment]
We're not dealing with AOSPA-L. At the moment its deprecated

**Pull request merged**
